### ISSUE TITLE
Links broken in Navigation bar

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/diverse-beam-search#5]
The links in the navigation bar are broken and needs to be prepended by `http://cloudcv.org/`

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure. :-)

**Comment by RishabhJain2018** [comment]
@deshraj I think the issue is already solved. Please refer to this [link](https://github.com/Cloud-CV/diverse-beam-search/blob/master/demo/templates/index.html#L35).

**Comment by deshraj** [comment]
Oh I just noticed that we haven't deployed it. Thanks. :-) 

Closing it.
